# insrall Ansible in Server
- name: install ansible
  hosts: localhost
  become: yes
  tasks:
  - name: install Ansible
    ansible.builtin.dnf:
      name: ansible
      state: present
  - name: verify ansible installed version
    ansible.builtin.command: ansible --version
    register: ansible_version

  - name: show print of anible version
    ansible.builtin.debug:
      msg: "{{ ansible_version.stdout }}"


